[package]
name = "pfc-steak"
version = "2.1.8"
authors = ["larry <gm@larry.engineer>", "PFC <pfc-validator@protonmail.com>"]
edition = "2018"
description = "Liquid steaking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://liquidsteaking.app"
repository = "https://github.com/PFC-developer/steak-contracts"

[dependencies]
cosmwasm-std = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cosmwasm-schema = { workspace = true }
