[package]
name = "dpow-miner-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
sha2 = "0.10.6"
hex = "0.4.3"
pfc-steak = { path = '../../packages/steak' }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"