[package]
name = "dpow-miner-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
sha2 = "0.10.6"
hex = "0.4.3"
pfc-steak = { path = '../../packages/steak' }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
anyhow = "1.0.51"
tokio = { version = "1.14.0", features = ["full"] }
futures = "0.3.18"
rand = "0.8.4"
async-std = { version = "1", features = ["attributes", "tokio1"] }
